# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: '[BUILD_SHARED_LIBS=${{ matrix.BUILD_SHARED_LIBS }}]'
    strategy:
      fail-fast: false
      matrix:
        BUILD_SHARED_LIBS: [ON, OFF]
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
          
      - name: Configure and Compile
        shell: cmd
        run: |
          :: Cleanup wrong python
          rmdir /S /Q C:\hostedtoolcache\windows\Python\3.10.5\
          call C:\dev\humble\ros2-windows\local_setup.bat
          mkdir build
          cd build
          cmake -G"Visual Studio 16 2019" -DBUILD_SHARED_LIBS:BOOL=${{ matrix.BUILD_SHARED_LIBS }} ..
          cmake --build . --config Release


